include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - .dart_tool/**
    - ios/**
    - android/**
    - web/**
    - linux/**
    - macos/**
    - windows/**

linter:
  rules:
    # ---- Qualidade de código ----
    always_declare_return_types: true
    always_use_package_imports: true
    avoid_dynamic_calls: true
    avoid_empty_else: true
    avoid_print: true
    avoid_unused_constructor_parameters: true
    cancel_subscriptions: true
    close_sinks: true

    # ---- Legibilidade ----
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_fields: true
    prefer_final_locals: true
    unnecessary_this: true

    # ---- Segurança e bugs comuns ----
    use_build_context_synchronously: true
    use_key_in_widget_constructors: true
    avoid_unnecessary_containers: true
    avoid_redundant_argument_values: true

    # ---- Organização ----
    directives_ordering: true
    sort_child_properties_last: true

    # ---- Performance Flutter ----
    sized_box_for_whitespace: true
    use_full_hex_values_for_flutter_colors: true
